[tool.poetry]
name = "pyrobot"
version = "0.1.0"
description = ""
authors = ["develophub <mixan_45@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
